### ISSUE TITLE
[Feature Request] Add ability to filter for custom NBT attributes

### ISSUE THREAD

**Issue by ghost** [Winds-Studio/Surf#3]
Add the ability to set a blacklist/whitelist for custom illegal attributes instead of filtering all attributes. 
This would enable server owners to configure themselves what they want to allow and what not.

**Comment by Dreeam-qwq** [comment]
Use [Panilla](https://www.spigotmc.org/resources/panilla-prevent-hacked-items.65694/) instead.

**Comment by Dreeam-qwq** [comment]
This feature is added since https://github.com/Winds-Studio/Surf/commit/16dfd5e2bac2f720a9bf2c22de90d2b62dbf31ff
